[POAE7-2793] logging refactor
intel/BDTK pull request #327
Opened 2023-01-12 09:32 UTC by harborn

### What changes were proposed in this pull request?

### Why are the changes needed?

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

### Which label does this PR belong to?

2023-01-13 01:25 UTC, jikunshang requested changes
Please provide more details in PR description.

2023-01-13 01:25 UTC, jikunshang commented on src/cider/exec/operator/aggregate/CiderAggSpillBufferMgr.cpp
> +    LOG(INFO) << "Create spill file: " << file_path.native() << " Fd=" << fd_;
try DLOG instead? https://github.com/google/glog#debug-mode-support

2023-01-13 01:25 UTC, jikunshang commented on src/cider/util/CMakeLists.txt
> +  folly
why need folly

2023-01-13 01:25 UTC, jikunshang commented on src/cider/benchmarks/CMakeLists.txt
> +target_link_libraries(jitlib_benchmark ${DEP_LIBS} folly fmt::fmt)
why need folly

2023-01-13 01:25 UTC, jikunshang commented on src/cider/tests/nextgen/functional/benchmark/CMakeLists.txt
> +                        cider_processor)
why remove this.

2023-01-13 01:25 UTC, jikunshang commented on src/cider/tests/CMakeLists.txt
> +  # add_subdirectory(benchmark)
why remove this.

2023-01-29 02:39 UTC, chaojun-zhang submitted a review, later dismissed

2023-01-31 00:38 UTC, jikunshang commented on src/cider/exec/operator/aggregate/CiderAggSpillBufferMgr.cpp
> +    LOG(INFO) << "Create spill file: " << file_path.native() << " Fd=" << fd_;
any update on this suggestion?

2023-01-31 01:10 UTC, winningsix commented on cpp/src/cider/tests/CiderLogTest.cpp
> +  // EXPECT_THROW({ LOG(FATAL) << "FATAL log"; }, CheckFatalException);
Why comment out?

2023-01-31 01:10 UTC, winningsix commented on cpp/src/cider/util/Logger.cpp
> +#if 0
what's our alternative to bypass log.stream?

2023-01-31 01:31 UTC, chaojun-zhang submitted a review, later dismissed
I'm ok to approve, please fix the conflict first

2023-01-31 01:33 UTC, jikunshang commented on src/cider/exec/operator/aggregate/CiderAggSpillBufferMgr.cpp
> +    LOG(INFO) << "Create spill file: " << file_path.native() << " Fd=" << fd_;
offline discussed, will  resolve this in later pr.

2023-01-31 02:02 UTC, jikunshang approved these changes

2023-01-31 02:07 UTC, winningsix approved these changes

2023-01-31 02:07 UTC, merged