[POAE7-2308]Transformer support multi-source Cider plan
intel/BDTK pull request #78
Opened 2022-10-19 02:11 UTC by XinDongIntel

### What changes were proposed in this pull request?
Change CiderPlanRewriter to support multi-source node rewriting.

### Why are the changes needed?
As V2S convertor Join support is done, change the CiderPlanRewriter to use the convertor and rewrite join pattern into  CiderPlanNode.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Will be tested as a part of Join-related tests.

### Which label does this PR belong to?
velox-plugin

2022-10-19 02:23 UTC, winningsix reviewed
Any chance to have some simple UTs covering this?

2022-10-19 02:23 UTC, winningsix commented on cider-velox/src/ciderTransformer/CiderPlanUtil.cpp
> +    return nullptr;
Any case we have condition ```newLeftSrc.first && newRightSrc.first``` stands false? If so, should we log an error msg here?

2022-10-20 00:49 UTC, winningsix submitted a review, later dismissed

2022-10-20 00:49 UTC, winningsix commented
Let's close code-style issue before merging.

2022-10-20 08:59 UTC, harborn requested changes

2022-10-20 08:59 UTC, harborn commented on cider-velox/src/ciderTransformer/CiderPlanUtil.cpp
> +  auto newLeftSrc = PlanUtil::findInNodeAddrMap(newSrcMap, leftSrcBranchId, 0);
I think a explicit type is better, do not use auto anywhere.

2022-10-25 00:24 UTC, winningsix commented
@XinDongIntel still has some issues around lint and code-style.

2022-10-25 07:09 UTC, harborn approved these changes

2022-10-25 07:12 UTC, winningsix approved these changes

2022-10-25 07:12 UTC, merged